name: Build LCM

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'  # This assumes that your version tags are prefixed with 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GCC
        uses: actions/setup-python@v2
        with:
          gcc-version: '11'  # Specify the GCC version you need

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential gcc-arm-none-eabi

      - name: Build project
        run: |
          cd LCM
          ls -la
          make

      # Additional steps to create a release and upload files
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload app.hex
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./LCM/Build/app.hex
          asset_name: app.hex
          asset_content_type: application/octet-stream